/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sources;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import com.formdev.flatlaf.*;
import java.awt.Color;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Abummoja
 */
public class MainFrame extends javax.swing.JFrame {

    ProgressDialog dmg = new ProgressDialog(this, false);
    public String dpath;
    public String orpath;
    String selectedd;
    String[] hst;
    //List<String> histt = new ArrayList<>(Arrays.asList(hst));
    String[] zips;
    String[] auds;
    String[] vids;
    String[] iapps;
    String[] pics;
    String[] docs;
    public static String user = System.getProperty("user.name");
    String os = System.getProperty("os.name");
    UserSettings uss = new UserSettings();
    FileOrganizer fo = new FileOrganizer();
    String[] dummy = {""};
    List<String> dmm = new ArrayList<>(Arrays.asList(dummy));

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        //String[] rec = pref.getByteArray("recentFiles", new Byte[]);
        fileListCpy.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        docDirTxt.setText(uss.getDir("doc"));
        audDirTxt.setText(uss.getDir("mp3"));
        picDirTxt.setText(uss.getDir("pic"));
        vidDirTxt.setText(uss.getDir("mp4"));
        appDirTxt.setText(uss.getDir("app"));
        rarDirTxt.setText(uss.getDir("aar"));
        orgBtn.setVisible(false);
        //recentsListView.setListData(hst);
        //DataBaseManager.creator();
        if(DataBaseManager.getHist().equals("")){
        
        }else{
            //hst = DataBaseManager.getHist();
        }
        fileListCpy.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                String selection = fileListCpy.getSelectedValue();
                System.out.println("Selected value is: " + selection);
                selectedd = selection;

                int v = Integer.parseInt(numcpy.getText());
                for (int i = 0; i < v; i++) {
                    String dm = String.format(selection + "(%d)", i);
                    dmm.add(dm);
                }
                dummy = dmm.toArray(new String[dmm.size()]);
                copyPreview.setListData(dummy);
            }
        });
       
    }

    /**
     * This method is called from within the constructor to initialize the
     * form.WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     *
     * @param ev
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingsGroup1 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        tabsPanel = new javax.swing.JTabbedPane();
        startPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        selectDirButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        propertiesText = new javax.swing.JScrollPane();
        propertiesText2 = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        homelble = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        origDuplicatePane = new javax.swing.JPanel();
        selectFileBtn = new javax.swing.JButton();
        srcFileTxt = new javax.swing.JTextField();
        generateBtn = new javax.swing.JButton();
        destTxt = new javax.swing.JTextField();
        destDirBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        numcpy = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        fileListCpy = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        multipSummary = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        copyPreview = new javax.swing.JList<>();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        origList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        newList = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        wordtxt = new javax.swing.JTextField();
        removeButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        newtxt = new javax.swing.JTextField();
        msgp = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        orgDestDir = new javax.swing.JTextField();
        orgSrcBtn = new javax.swing.JButton();
        orgBtn = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        orgDirInfo = new javax.swing.JTextArea();
        orgState = new javax.swing.JLabel();
        orgProgBar = new javax.swing.JProgressBar();
        jScrollPane4 = new javax.swing.JScrollPane();
        orgCmplete = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        docDirTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        docDirBtn = new javax.swing.JButton();
        picDirTxt = new javax.swing.JTextField();
        picDirBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        vidDirTxt = new javax.swing.JTextField();
        vidDirBtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        audDirTxt = new javax.swing.JTextField();
        audDirBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        rarDirTxt = new javax.swing.JTextField();
        rarDirBtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        appDirTxt = new javax.swing.JTextField();
        appDirBtn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        themeBx = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Advance File Handler - Premium Software(TM)");
        setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 10)); // NOI18N
        setResizable(false);

        jLabel1.setText("Advanced File Handler");

        jLabel2.setText("This tool can rename many files at once, multiply files, change multiple files extension and much more!");

        jLabel3.setText("Select a working directory to continue");

        selectDirButton.setText("Select");
        selectDirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectDirButtonActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(153, 153, 255));
        jLabel4.setText("Properties:");

        propertiesText2.setEditable(false);
        propertiesText2.setColumns(20);
        propertiesText2.setRows(5);
        propertiesText.setViewportView(propertiesText2);

        homelble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/assets/filestudiobg.png"))); // NOI18N
        homelble.setIconTextGap(0);

        jLabel22.setText("Logged in as: "+user);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(homelble, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addGap(17, 17, 17))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homelble, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel22)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout startPaneLayout = new javax.swing.GroupLayout(startPane);
        startPane.setLayout(startPaneLayout);
        startPaneLayout.setHorizontalGroup(
            startPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startPaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(257, 257, 257))
            .addGroup(startPaneLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(startPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(startPaneLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(startPaneLayout.createSequentialGroup()
                        .addGroup(startPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(startPaneLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(47, 47, 47))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startPaneLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)))
                        .addComponent(selectDirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(296, Short.MAX_VALUE))))
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(propertiesText, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        startPaneLayout.setVerticalGroup(
            startPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPaneLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(startPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectDirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertiesText, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabsPanel.addTab("Start page", startPane);

        jLabel6.setText("Use this page to duplicate a file and create multiple copies of it in just a short time");

        origDuplicatePane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Original file"));

        selectFileBtn.setText("Browse");
        selectFileBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        srcFileTxt.setText("Selected file at");

        generateBtn.setText("Generate copies");
        generateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generateBtnMouseClicked(evt);
            }
        });

        destTxt.setText("Generate copies in");

        destDirBtn.setText("Browse");
        destDirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destDirBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("Enter the number of copies to be produced");

        numcpy.setText("2");
        numcpy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numcpyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout origDuplicatePaneLayout = new javax.swing.GroupLayout(origDuplicatePane);
        origDuplicatePane.setLayout(origDuplicatePaneLayout);
        origDuplicatePaneLayout.setHorizontalGroup(
            origDuplicatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, origDuplicatePaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(generateBtn)
                .addGap(143, 143, 143))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, origDuplicatePaneLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(numcpy, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(origDuplicatePaneLayout.createSequentialGroup()
                .addGroup(origDuplicatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(srcFileTxt)
                    .addComponent(destTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(origDuplicatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(destDirBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selectFileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        origDuplicatePaneLayout.setVerticalGroup(
            origDuplicatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(origDuplicatePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(origDuplicatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(srcFileTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(origDuplicatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(destTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destDirBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(origDuplicatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(numcpy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(generateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        fileListCpy.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        fileListCpy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fileListCpyMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(fileListCpy);

        multipSummary.setColumns(20);
        multipSummary.setRows(5);
        jScrollPane6.setViewportView(multipSummary);

        copyPreview.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane9.setViewportView(copyPreview);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("The files in the list below are\nthe preview of what will be \ncreated");
        jTextArea2.setToolTipText("Hint");
        jTextArea2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextArea2.setDisabledTextColor(new java.awt.Color(102, 102, 255));
        jTextArea2.setEnabled(false);
        jTextArea2.setFocusable(false);
        jTextArea2.setHighlighter(null);
        jTextArea2.setRequestFocusEnabled(false);
        jScrollPane10.setViewportView(jTextArea2);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("Hint: Click one file here to \nsee its copies preview in the\nother list.");
        jTextArea3.setToolTipText("Hint");
        jTextArea3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextArea3.setDisabledTextColor(new java.awt.Color(102, 102, 255));
        jTextArea3.setEnabled(false);
        jTextArea3.setFocusable(false);
        jTextArea3.setHighlighter(null);
        jTextArea3.setRequestFocusEnabled(false);
        jScrollPane11.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(origDuplicatePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 15, Short.MAX_VALUE)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(origDuplicatePane, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
        );

        tabsPanel.addTab("File multiplier", jPanel2);

        origList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(origList);

        newList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(newList);

        jLabel5.setText("Original file names                                       New names");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Enter a word that is common in many file\nnames below and select remove to get rid\nof it at once from all the file names");
        jTextArea1.setBorder(null);
        jScrollPane3.setViewportView(jTextArea1);

        wordtxt.setText("Common word e.g y2mate.com");
        wordtxt.setToolTipText("Enter the word");
        wordtxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        wordtxt.setDragEnabled(true);
        wordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordtxtActionPerformed(evt);
            }
        });

        removeButton.setText("Remove word");
        removeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeButtonMouseClicked(evt);
            }
        });
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Replace the word with :");

        newtxt.setText("new word or leave blank");

        msgp.setText(".");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(msgp, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(removeButton))))
                                .addGap(0, 12, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(wordtxt)
                                    .addComponent(newtxt, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(msgp, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(351, Short.MAX_VALUE))
        );

        tabsPanel.addTab("Word remover", jPanel1);

        jLabel9.setText("Here you can automatically move files from a specific directory to the desired directory such as the mixed up files from your Downloads");

        jLabel10.setText("folder to Music, Videos, Documents and Pictures.");

        orgSrcBtn.setText("Browse");
        orgSrcBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orgSrcBtnMouseClicked(evt);
            }
        });

        orgBtn.setText("Organize the files");
        orgBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orgBtnMouseClicked(evt);
            }
        });
        orgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgBtnActionPerformed(evt);
            }
        });

        jLabel21.setText("Organize files contained at:");

        orgDirInfo.setEditable(false);
        orgDirInfo.setColumns(20);
        orgDirInfo.setRows(5);
        orgDirInfo.setText("Path:\nName:\nSize:\nDate created:\nLast modified:\nContains:\n");
        jScrollPane8.setViewportView(orgDirInfo);

        orgState.setFocusable(false);

        orgCmplete.setEditable(false);
        orgCmplete.setColumns(20);
        orgCmplete.setRows(5);
        orgCmplete.setText("Succesfully organized...files\nfound...audio files\n...documents\n...pictures etc.");
        jScrollPane4.setViewportView(orgCmplete);

        jButton5.setText("Process folder");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(orgState, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(orgDestDir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(orgSrcBtn))
                            .addComponent(orgBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(orgProgBar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(182, 182, 182))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orgSrcBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orgDestDir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orgBtn)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orgState)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(orgProgBar, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        jLabel9.getAccessibleContext().setAccessibleName("Here you can automatically move files from a specific directory to the desired directory (such as the mixed up files from your Downloads\n");

        tabsPanel.addTab("Organizer", jPanel4);

        jLabel11.setText("Default Documents directory");

        docDirBtn.setText("Browse");

        picDirBtn.setText("Browse");

        jLabel12.setText("Default Pictures directory");

        vidDirBtn.setText("Browse");

        jLabel13.setText("Default Videos directory");

        audDirBtn.setText("Browse");

        jLabel14.setText("Default Music directory");

        rarDirBtn.setText("Browse");

        jLabel15.setText("Default Archives directory");

        jLabel16.setForeground(new java.awt.Color(153, 153, 255));
        jLabel16.setText("zip;rar;jar;gz;7z;tar");

        appDirBtn.setText("Browse");

        jLabel17.setText("Applications(Software) directory");

        jLabel18.setForeground(new java.awt.Color(153, 153, 255));
        jLabel18.setText(".exe .msi .apk .com");

        jTextArea4.setEditable(false);
        jTextArea4.setColumns(20);
        jTextArea4.setForeground(new java.awt.Color(242, 242, 242));
        jTextArea4.setRows(5);
        jTextArea4.setText("This page contains options to change where organizer places\nfiles and more file options.");
        jTextArea4.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        jTextArea4.setEnabled(false);
        jTextArea4.setFocusable(false);
        jScrollPane7.setViewportView(jTextArea4);

        jButton1.setText("Cancel");

        jButton2.setText("Restore Default");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));

        jButton3.setBackground(new java.awt.Color(102, 102, 255));
        jButton3.setText("Save");

        jLabel19.setText("When sorting out do not sort the following");

        jCheckBox1.setText("All");

        jCheckBox2.setText("Music");

        jCheckBox3.setText("Pictures");

        jCheckBox4.setText("Videos");

        jCheckBox5.setText("Documents");

        jCheckBox6.setText("Archives");

        jCheckBox7.setText("Applications");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jCheckBox1)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox4)
                            .addComponent(jCheckBox5)
                            .addComponent(jCheckBox6)
                            .addComponent(jCheckBox7))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBox7))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel18))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(91, 91, 91)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 129, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(appDirTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(appDirBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rarDirTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rarDirBtn))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(docDirTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(docDirBtn))
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(audDirTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                    .addComponent(picDirTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vidDirTxt, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(picDirBtn)
                                    .addComponent(vidDirBtn)
                                    .addComponent(audDirBtn)))
                            .addComponent(jLabel14)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(docDirTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(docDirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(picDirBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(picDirTxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vidDirBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vidDirTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(audDirBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(audDirTxt)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rarDirBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(rarDirTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(appDirBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(appDirTxt))
                .addGap(192, 192, 192)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tabsPanel.addTab("File Options", jPanel3);

        jLabel20.setText("Theme");

        jButton4.setText("Save");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton6.setText("Restore Defaults");

        themeBx.setText("Use light theme");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(536, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(themeBx)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(themeBx)
                .addGap(58, 58, 58)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 519, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton6)))
        );

        tabsPanel.addTab("Settings", jPanel5);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsPanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(tabsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* static void setBg(){
        ImageIcon imageIcon = new ImageIcon(new ImageIcon("/sources/assets/filestudiobg.png").getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
        homelble.setIcon(imageIcon);
    }*/

    private void selectDirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectDirButtonActionPerformed
        // TODO add your handling code here:
        File[] fl;
        String props;
        int i;
        final JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int x = chooser.showDialog(jPanel1, "Use this Folder");
        if (x == JFileChooser.APPROVE_OPTION) {
            File wdir = chooser.getSelectedFile();
            propertiesText2.setText("Please wait...");
            if (wdir.isDirectory()) {
                //use array list to get the length
                fl = wdir.listFiles();
                i = fl.length;
                String sz = FileUtil.getFileSize(wdir.getPath());
                props = "File name: " + wdir.getName() + "\nSize:" + sz + "\nPath : " + wdir.getPath() + "\nItems: " + i + "\nDate created : " + wdir.lastModified();

                propertiesText2.setText(props);
                dpath = wdir.getPath();
                loadFiles(dpath);
            } else {
                props = "File name: " + wdir.getName() + "\nPath : " + wdir.getPath();
                propertiesText2.setText(props);
                dpath = wdir.getPath();
                loadFiles(dpath);
            }

            srcFileTxt.setText(dpath);
            destTxt.setText(dpath);
            orgDestDir.setText(dpath);
            
            //DataBaseManager.add(dpath);
        } else {
            //if user selected cancel
        }

    }//GEN-LAST:event_selectDirButtonActionPerformed

    public void loadFiles(String mpath) {
        File f = new File(mpath);
        String[] strl = f.list();
        origList.setListData(strl);
        fileListCpy.setListData(strl);

    }
    private void wordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wordtxtActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeButtonActionPerformed

    private void removeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeButtonMouseClicked
        // TODO add your handling code here:
        String ol = wordtxt.getText().toString();
        String nw = newtxt.getText().toString();
        renameFiles(dpath, ol, nw);
        updateList(dpath);
    }//GEN-LAST:event_removeButtonMouseClicked

    private void destDirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destDirBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destDirBtnActionPerformed

    private void orgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orgBtnActionPerformed

    private void orgSrcBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orgSrcBtnMouseClicked
        // TODO add your handling code here:
        File[] fl;
        String props;
        int i;
        final JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int x = chooser.showDialog(jPanel1, "Use this Folder");
        if (x == JFileChooser.APPROVE_OPTION) {
            File wdir = chooser.getSelectedFile();
            propertiesText2.setText("Please wait...");
            if (wdir.isDirectory()) {
                //use array list to get the length
                fl = wdir.listFiles();
                i = fl.length;
                props = "File name: " + wdir.getName() + "\nPath : " + wdir.getPath() + "\nItems: " + i + "\nDate created : " + wdir.lastModified();
            } else {
                props = "File name: " + wdir.getName() + "\nPath : " + wdir.getPath();

            }
            orpath = wdir.getPath();
            orgDestDir.setText(orpath);
        } else {
            //if user selected cancel
        }
    }//GEN-LAST:event_orgSrcBtnMouseClicked

    private void orgBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orgBtnMouseClicked
        // TODO add your handling code here:
        String fss = "C:\\Users\\" + user + "\\Music";
        String o = orgDestDir.getText();
        try {
            fo.moveFi(uss.getDir("aar"), zips);
            orgCmplete.setText("Moved: " + zips.length + " archives");
            fo.moveFi(uss.getDir("mp4"), vids);
            orgCmplete.setText(orgCmplete.getText() + "\nMoved: " + vids.length + " videos");
            fo.moveFi(uss.getDir("mp3"), auds);
            orgCmplete.setText(orgCmplete.getText() + "\nMoved: " + auds.length + " Music");
            fo.moveFi(uss.getDir("doc"), docs);
            orgCmplete.setText(orgCmplete.getText() + "\nMoved: " + docs.length + " Documents");
            fo.moveFi(uss.getDir("app"), iapps);
            orgCmplete.setText(orgCmplete.getText() + "\nMoved: " + iapps.length + " executables");
            fo.moveFi(uss.getDir("pic"), pics);
            orgCmplete.setText(orgCmplete.getText() + "\nMoved: " + pics.length + " pics");
            //orgCmplete.setText("Success!");
        } catch (IOException ex) {
            orgCmplete.setText(ex.getMessage());
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        updateOldList(o);
    }//GEN-LAST:event_orgBtnMouseClicked

    public void organizerMain() {
        // TODO add your handling code here:
        orgState.setText("Wait...");
        String fss1 = orgDestDir.getText();
        if ("".equals(fss1)) {
            orgDestDir.setText("You must select a folder to operate.");
        } else {
            orgBtn.setVisible(true);
            orgState.setText("Processing files...");
            String fss = "C:\\Users\\" + user + "\\Documents";

            //fss1 should be the value of dir text
            //music
            loadF(FileUtil.archex, fss1);
            zips = fo.files;
            orgDirInfo.setText("Found: " + zips.length + " archives.");
            fo.clearList();
            for (String sg : zips) {
                System.out.println(sg);
            }
            orgProgBar.setValue(20);
            fo.clearList();
            //audio
            loadF(FileUtil.audex, fss1);
            auds = fo.files;
            orgDirInfo.setText(orgDirInfo.getText() + "\n" + "Found: " + auds.length + " music.");
            fo.clearList();
            for (String sg : auds) {
                System.out.println(sg);
            }
            orgProgBar.setValue(20 + orgProgBar.getValue());
            fo.clearList();
            //videos
            loadF(FileUtil.videx, fss1);
            vids = fo.files;
            orgDirInfo.setText(orgDirInfo.getText() + "\n" + "Found: " + vids.length + " videos.");
            fo.clearList();
            for (String sg : vids) {
                System.out.println(sg);
            }
            orgProgBar.setValue(20 + orgProgBar.getValue());
            fo.clearList();
            //pictures
            loadF(FileUtil.picex, fss1);
            pics = fo.files;
            orgDirInfo.setText(orgDirInfo.getText() + "\n" + "Found: " + pics.length + " pictures.");
            fo.clearList();
            for (String sg : pics) {
                System.out.println(sg);
            }
            orgProgBar.setValue(20 + orgProgBar.getValue());
            fo.clearList();
            //documents
            loadF(FileUtil.docex, fss1);
            docs = fo.files;
            orgDirInfo.setText(orgDirInfo.getText() + "\n" + "Found: " + docs.length + " documents.");
            fo.clearList();
            for (String sg : docs) {
                System.out.println(sg);
            }
            orgProgBar.setValue(20 + orgProgBar.getValue());
            fo.clearList();
            //apps
            loadF(FileUtil.appex, fss1);
            iapps = fo.files;
            orgDirInfo.setText(orgDirInfo.getText() + "\n" + "Found: " + iapps.length + " executables.");
            fo.clearList();
            for (String sg : iapps) {
                System.out.println(sg);
            }
            orgProgBar.setValue(10 + orgProgBar.getValue());
            fo.clearList();
            orgProgBar.setIndeterminate(false);
            orgProgBar.setMaximum(100);
            orgProgBar.setValue(100);
            //dmg.setVisible(false);
        }

    }

    //jbutton5 is the process dir button!
    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        //dmg.setVisible(true);
        orgProgBar.setIndeterminate(true);
        organizerMain();
        uss.createDir(uss.dirs);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        if (themeBx.isSelected()) {
            uss.setTheme(true);
        } else {
            uss.setTheme(false);
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void numcpyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numcpyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numcpyActionPerformed

    private void generateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateBtnMouseClicked
        try {
            // TODO add your handling code here:
            cpy(srcFileTxt.getText() +"\\"+ selectedd, destTxt.getText());
            System.out.println("Duplicating: " + srcFileTxt.getText() + selectedd);
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_generateBtnMouseClicked

    private void fileListCpyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileListCpyMouseClicked
        // TODO add your handling code here:
        int itm = fileListCpy.getSelectedIndex();
        String theFile;
        //theFile = fileListCpy[itm];
    }//GEN-LAST:event_fileListCpyMouseClicked

    public void cpy(String orifinalFile, String newFilePath) throws IOException {
        File origi = new File(orifinalFile);
        File newFile = new File(newFilePath);
        Path pathh = Paths.get(orifinalFile);
        String extension = "";

// get the file name
        String fileName = pathh.getFileName().toString();

// split the file name into parts using the dot (.) character as separator
        String[] parts = fileName.split("\\.");

// if there are at least two parts, the last part is the extension
        if (parts.length >= 2) {
            extension = parts[parts.length - 1];
        }

        System.out.println("File extension: " + extension);
        String origiName = origi.getName();
        int numcopies;
        if (numcpy.getText().equals("")) {
            numcpy.setText("Please enter a number");
            numcpy.requestFocus();
        } else {
            numcopies = Integer.parseInt(numcpy.getText());
            for (int cp = 0; cp < numcopies; cp++) {
                String newFileCopyName = String.format(newFilePath + "\\" + origiName + "(%d)." + extension, cp);
                File newF = new File(newFileCopyName);
                Files.copy(origi.toPath(), newF.toPath());
            }
            //fileListCpy.setListData(vids);
            updateList(dpath);
            updateOldList(dpath);
        }
    }

    public void loadF(String ext, String fssd) {
        try {
            fo.listFiles(ext, fssd);
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void organizeFiles(String path, String dst) throws IOException {
        String audxt = FileUtil.audex;
        // String vidxt, picxt, docxt, archxt;

        FileUtil.iterateAndFilter(path, audxt);
        String fll[] = FileUtil.ff;
        /* for(String s:fll){
            FileUtil.moveFiles(s, dst);
        }*/
        orgCmplete.setText(FileUtil.sts);
    }

    public void renameFiles(String path, String old, String newn) {
        FileRenamer rn = new FileRenamer();
        String result = rn.renameBulk(path, old, newn);
        System.out.println(result);
        msgp.setText(result);
    }

    public void updateOldList(String mpath) {
        File f = new File(mpath);
        String[] strl = f.list();
        origList.setListData(strl);
        fileListCpy.setListData(strl);
    }

    public void updateList(String mpath) {

        File f = new File(mpath);
        String[] strl = f.list();
        newList.setListData(strl);
        fileListCpy.setListData(strl);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        if (UserSettings.isDark) {
            FlatDarkLaf.setup();
            UIManager.put("TabbedPane.selectedBackground", Color.BLACK);
        } else {
            FlatLightLaf.setup();
            UIManager.put("TabbedPane.selectedBackground", Color.WHITE);
        }
        UIManager.put("Button.arc", 10);
        UIManager.put("TextComponent.arc", 10);
        UIManager.put("Component.outerFocusWidth", 2);
        UIManager.put("Component.innerFocusWidth", 2);
        UIManager.put("Component.hideMnemonics", false);

        UIManager.put("TabbedPane.showTabSeparators", true);

        // setBg();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton appDirBtn;
    public javax.swing.JTextField appDirTxt;
    public javax.swing.JButton audDirBtn;
    public javax.swing.JTextField audDirTxt;
    public javax.swing.JList<String> copyPreview;
    public javax.swing.JButton destDirBtn;
    public javax.swing.JTextField destTxt;
    public javax.swing.JButton docDirBtn;
    public javax.swing.JTextField docDirTxt;
    public javax.swing.JList<String> fileListCpy;
    public javax.swing.JButton generateBtn;
    public static javax.swing.JLabel homelble;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    public javax.swing.JButton jButton6;
    public javax.swing.JCheckBox jCheckBox1;
    public javax.swing.JCheckBox jCheckBox2;
    public javax.swing.JCheckBox jCheckBox3;
    public javax.swing.JCheckBox jCheckBox4;
    public javax.swing.JCheckBox jCheckBox5;
    public javax.swing.JCheckBox jCheckBox6;
    public javax.swing.JCheckBox jCheckBox7;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JPanel jPanel6;
    public javax.swing.JPanel jPanel7;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane10;
    public javax.swing.JScrollPane jScrollPane11;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JScrollPane jScrollPane7;
    public javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JScrollPane jScrollPane9;
    public javax.swing.JTextArea jTextArea1;
    public javax.swing.JTextArea jTextArea2;
    public javax.swing.JTextArea jTextArea3;
    public javax.swing.JTextArea jTextArea4;
    public javax.swing.JPanel mainPanel;
    public javax.swing.JLabel msgp;
    public javax.swing.JTextArea multipSummary;
    public javax.swing.JList<String> newList;
    public javax.swing.JTextField newtxt;
    public javax.swing.JTextField numcpy;
    public javax.swing.JButton orgBtn;
    public javax.swing.JTextArea orgCmplete;
    public javax.swing.JTextField orgDestDir;
    public javax.swing.JTextArea orgDirInfo;
    public javax.swing.JProgressBar orgProgBar;
    public javax.swing.JButton orgSrcBtn;
    public javax.swing.JLabel orgState;
    public javax.swing.JPanel origDuplicatePane;
    public javax.swing.JList<String> origList;
    public javax.swing.JButton picDirBtn;
    public javax.swing.JTextField picDirTxt;
    public javax.swing.JScrollPane propertiesText;
    public javax.swing.JTextArea propertiesText2;
    public javax.swing.JButton rarDirBtn;
    public javax.swing.JTextField rarDirTxt;
    public javax.swing.JButton removeButton;
    public javax.swing.JButton selectDirButton;
    public javax.swing.JButton selectFileBtn;
    public javax.swing.ButtonGroup settingsGroup1;
    public javax.swing.JTextField srcFileTxt;
    public javax.swing.JPanel startPane;
    public javax.swing.JTabbedPane tabsPanel;
    public javax.swing.JCheckBox themeBx;
    public javax.swing.JButton vidDirBtn;
    public javax.swing.JTextField vidDirTxt;
    public javax.swing.JTextField wordtxt;
    // End of variables declaration//GEN-END:variables
}
